// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1CGWU0jlMhCOQNj9s0WC7R4U0g6dEMyM',
    appId: '1:632835404179:web:fe26f7b90af2ab5fa6b866',
    messagingSenderId: '632835404179',
    projectId: 'chatapp-97ade',
    authDomain: 'chatapp-97ade.firebaseapp.com',
    storageBucket: 'chatapp-97ade.appspot.com',
    measurementId: 'G-M434D14TMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgBygL8L-U1L4NdYpZKLjA_qP4SU9mkHU',
    appId: '1:632835404179:android:664d8cba9183708aa6b866',
    messagingSenderId: '632835404179',
    projectId: 'chatapp-97ade',
    storageBucket: 'chatapp-97ade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthQ-q4b9lZ9SZM9Vq06Nq6oH2OC1w9GY',
    appId: '1:632835404179:ios:b1131c809d1597aea6b866',
    messagingSenderId: '632835404179',
    projectId: 'chatapp-97ade',
    storageBucket: 'chatapp-97ade.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCthQ-q4b9lZ9SZM9Vq06Nq6oH2OC1w9GY',
    appId: '1:632835404179:ios:534ba0644e7535dba6b866',
    messagingSenderId: '632835404179',
    projectId: 'chatapp-97ade',
    storageBucket: 'chatapp-97ade.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
